language: python
sudo: false

python:
  - "2.7"

env:
  - TOXENV=django18
  - TOXENV=django110
  - TOXENV=django111
  - TOXENV=quality

before_install:
    - "export DISPLAY=:99"
    - "sh -e /etc/init.d/xvfb start"

addons:
  firefox: '58.0.2'

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success: coveralls
